version: 2.1
orbs:
  architect: giantswarm/architect@2.5.0

workflows:
  build:
    jobs:
      - architect/go-build:
          name: go-build
          binary: azure-disk-attacher
          filters:
            tags:
              only: /^v.*/

      - architect/push-to-docker:
          context: architect
          name: push-to-quay
          image: "quay.io/giantswarm/azure-disk-attacher"
          username_envar: "QUAY_USERNAME"
          password_envar: "QUAY_PASSWORD"
          requires:
            - go-build
          filters:
            tags:
              only: /^v.*/
